const axios = require('axios');
const axiosRetry = require('axios-retry').default;
const { LinearClient } = require('@linear/sdk');
// Load environment variables from .env.local if present
require('dotenv').config({ path: '.env.local' });


// --- Configuration (with .trim() to fix "Invalid character" errors) ---
const VERCEL_TOKEN = (process.env.VERCEL_TOKEN || '').trim();
const VERCEL_PROJECT_ID = (process.env.VERCEL_PROJECT_ID || '').trim();
const LINEAR_API_KEY = (process.env.LINEAR_API_KEY || '').trim();
const LINEAR_TEAM_ID = (process.env.LINEAR_TEAM_ID || '').trim();

// --- Resilience Setup ---
// Configure axios with retries for unstable network (high packet loss)
axiosRetry(axios, { 
    retries: 5, 
    retryDelay: axiosRetry.exponentialDelay,
    onRetry: (retryCount, error) => {
        console.log(`⚠️ Network glitch (packet loss?). Retrying... (${retryCount}/5)`);
    },
    retryCondition: (error) => {
        // Retry on network errors or timeouts
        return axiosRetry.isNetworkOrIdempotentRequestError(error) || error.code === 'ECONNABORTED';
    }
});

// Setup Linear Client
// Note: Linear SDK uses global fetch if available. In Node 21+, it uses native fetch.
// To make Linear SDK more robust in this environment, we override the fetch global.
global.fetch = async (url, options) => {
    try {
        const response = await axios({
            url: url.toString(),
            method: options.method || 'GET',
            data: options.body,
            headers: options.headers,
            timeout: 30000 // 30s timeout
        });
        
        return {
            ok: response.status >= 200 && response.status < 300,
            status: response.status,
            statusText: response.statusText,
            headers: {
                get: (name) => response.headers[name.toLowerCase()]
            },
            json: async () => response.data,
            text: async () => JSON.stringify(response.data)
        };
    } catch (error) {
        if (error.response) {
            return {
                ok: false,
                status: error.response.status,
                statusText: error.response.statusText,
                headers: {
                    get: (name) => error.response.headers[name.toLowerCase()]
                },
                json: async () => error.response.data,
                text: async () => JSON.stringify(error.response.data)
            };
        }
        throw error;
    }
};

const linearClient = new LinearClient({ apiKey: LINEAR_API_KEY });

async function checkVercelErrors() {
    console.log(`🔍 Monitoring Vercel Project: ${VERCEL_PROJECT_ID}`);
    
    try {
        // 1. Fetch failed deployments from Vercel
        const vercelRes = await axios.get(
            `https://api.vercel.com/v6/deployments?projectId=${VERCEL_PROJECT_ID}&state=ERROR`, 
            {
                headers: { "Authorization": `Bearer ${VERCEL_TOKEN}` },
                timeout: 30000
            }
        );

        const deployments = vercelRes.data.deployments || [];
        if (deployments.length === 0) {
            console.log("✅ No new failed deployments discovered.");
            return;
        }

        console.log(`🚩 Found ${deployments.length} failed deployments. Synchronizing with Linear...`);

        // 2. Resolve Team ID
        let teamId = LINEAR_TEAM_ID;
        if (!teamId) {
            try {
                const teams = await linearClient.teams();
                teamId = teams.nodes[0]?.id;
                if (!teamId) throw new Error("No Linear team found in workspace.");
                console.log(`ℹ️ Defaulting to Team: ${teams.nodes[0].name}`);
            } catch (err) {
                console.error("❌ Failed to fetch Linear teams. Check your API Key scopes (requires `read`).");
                throw err;
            }
        }

        // 3. Process each error (Oldest first for chronological order)
        for (const dep of [...deployments].reverse()) {
            const branchName = dep.meta?.githubCommitRef || 'unknown';
            const expectedTitle = `Vercel Error: ${branchName}`;

            // Deduplication Check: Search for Deployment ID in description
            const search = await linearClient.issues({ 
                filter: { description: { contains: dep.uid } } 
            });

            if (search.nodes && search.nodes.length > 0) {
                console.log(`⏭️ Skipping ${dep.uid} (${branchName}): Issue already tracked.`);
                continue;
            }

            // Construct detail-rich description (Whitelisted fields for privacy)
            const description = `
### Vercel Deployment Failure
- **Branch:** \`${branchName}\`
- **Deployment ID:** \`${dep.uid}\`
- **URL:** [View Deployment](https://${dep.url})
- **Commit:** ${dep.meta?.githubCommitMessage || 'No message'}
- **Author:** ${dep.meta?.githubCommitAuthorName || 'Unknown'}

---
*Generated by Vercel Monitor locally.*
            `.trim();

            console.log(`🚀 Creating Linear issue for ${dep.uid}...`);
            await linearClient.createIssue({
                teamId: teamId,
                title: expectedTitle,
                description: description,
                priority: 1 // High Priority
            });
        }

        console.log("✨ All failed deployments processed successfully.");

    } catch (err) {
        console.error("❌ Fatal Error in Workflow:");
        if (err.response) {
            console.error(`Status: ${err.response.status}`);
            console.error(`Message: ${JSON.stringify(err.response.data)}`);
        } else {
            console.error(err.message);
        }
        process.exit(1);
    }
}

// Ensure environment variables are loaded before running
const isCI = process.env.GITHUB_ACTIONS === 'true';

if (!VERCEL_TOKEN || !VERCEL_PROJECT_ID || !LINEAR_API_KEY) {
    console.error("❌ Execution Aborted: Missing required environment variables.");
    if (isCI) {
        console.error("   Please check your GitHub Repository Secrets for: VERCEL_TOKEN, VERCEL_PROJECT_ID, and LINEAR_API_KEY.");
    } else {
        console.error("   Please ensure your .env.local file contains: VERCEL_TOKEN, VERCEL_PROJECT_ID, and LINEAR_API_KEY.");
    }
    process.exit(1);
}

checkVercelErrors();